### ISSUE TITLE
[dart-sass]: `hoistUseStatements` causes problems with @use ... with()

### ISSUE THREAD

**Issue by tomas-hartman** [shakacode/sass-resources-loader#135]
Hi, I encountered a problem when using the `hoistUseStatements` option when I need to use imported variables inside `with` statement. Compilation ends up with `SassError: There is no module with the namespace "colors".` error.

I suppose this is because `resources` are `@import`ed, so they are not available at the time of compilation of `@use`s. (Of course it also fails when not using `hoistUseStatements`, because `SassError: @use rules must be written before any other rules.`). 

I'd suggest adding some "importWithUse" switch or "usedResources", to allow the import to be at the very beginning of the file. This might also require adding some options for `@forward` later.

## Example

```js
// webpack loaders settings

{
  test: /\.scss$/,
  loader: 'sass-resources-loader',
  options: {
    resources: "_colors.scss",
    hoistUseStatements: true
  }
}
```

```scss
// _colors.scss (simplified)

$dark-blue: blue;
$dark-orange: orange;
$black: black;

```

```scss
// webpack using sass-resources-loader

// beginning of file
@use 'bootstrap-base' with (
  $dark: colors.$dark-blue,
  $primary: colors.$dark-orange,
  $secondary: colors.$black,
);

other-selectors-mixins-etc {
 // ...
}

// -> SassError: There is no module with the namespace "colors".
```
